console.log(" ////////////////////////");
console.log("||  Victory is mine!   ||");
console.log(" \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ ");
console.log(" ////////////////////////");
console.log("||  Victory is mine!   ||");
console.log(" \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ ");
console.log(" ////////////////////////");
console.log("||  Victory is mine!   ||");
console.log(" \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ ");
console.log(" ////////////////////////");
console.log("||  Victory is mine!   ||");
console.log(" \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ ");